export const ADD_USER_CREDENTIAL = "ADD_USER_CREDENTIAL";
export const CLEAR_USER_CREDENTIAL = "CLEAR_USER_CREDENTIAL";

export const ADD_CLASSES = "ADD_CLASSES";
export const ADD_STUDENTS = "ADD_STUDENTS";
export const CLEAR_TABLE_DATA = "CLEAR_TABLE_DATA";
